language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user-service ./udagram-api-user-service
  - docker build -t udagram-api-feed-service ./udagram-api-feed-service
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag reverseproxy quanlm11/reverseproxy:v1
  - docker tag udagram-api-user-service quanlm11/udagram-api-user-service:v1
  - docker tag udagram-api-feed-service quanlm11/udagram-api-feed-service:v1
  - docker tag udagram-frontend quanlm11/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple-node
  - docker push quanlm11/reverseproxy:v1
  - docker push quanlm11/udagram-api-user-service:v1
  - docker push quanlm11/udagram-api-feed-service:v1
  - docker push quanlm11/udagram-frontend:v1

