version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user-service
    image: udagram-api-user-service
  backend_feed:
    build:
      context: ./udagram-api-feed-service
    image: udagram-api-feed-service
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local